{% set name = "torchx" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/torchx/archive/v{{ version }}.tar.gz
  sha256: 6a28e2a84dc9955856653fc6ce669fa36e522db82698426ace0ea54b0a02f9b8

build:
  entry_points:
    - torchx = torchx.cli.main:main
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - docker-py
    - docstring_parser >=0.8.1
    - filelock
    - fsspec >=2023.10.0
    - importlib-metadata
    - pyre-extensions
    - python >={{ python_min }}
    - pyyaml
    - tabulate
    - urllib3 >=1.21.1,<1.27

test:
  imports:
    - torchx
  commands:
    - pip check
    - torchx -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytorch/torchx
  summary: A universal job launcher for PyTorch applications
  license: BSD 3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
